dataset=read.csv('Phishing.csv') 
   dataset = na.omit(dataset)
 dataset$class=factor(dataset$class,levels = c(0,1))
library(caTools)
set.seed(123)
   split= sample.split(dataset$class,SplitRatio = 0.75)
 training_set = subset(dataset, split == TRUE)
 test_set = subset(dataset, split == FALSE)
dataframe<-data.frame(Querylength=78,domain_token_count=78,path_token_count=90,longdomaintokenlen=7,avgpathtokenlen=79,tld=899,charcompvowels=79,charcompace=789,ldl_url=7,ldl_path=7,ldl_getArg=898,dld_path=78,dld_getArg=78,pathLength=788,subDirLen=78,this.fileExtLen=78,ArgLen=7899,ArgUrlRatio=79,domainUrlRatio=79,pathDomainRatio=978,NumberofDotsinURL=9,CharacterContinuityRate=87,URL_DigitCount=8,Extension_DigitCount=7,URL_Letter_Count=98,host_letter_count=78,Filename_LetterCount=87,Query_LetterCount=89,Domain_LongestWordLength=78,Path_LongestWordLength=88,Arguments_LongestWordLength=8,URL_sensitiveWord=1,spcharUrl=9,delimeter_path=89,NumberRate_URL=87,NumberRate_FileName=8,NumberRate_AfterPath=87,SymbolCount_URL=98,SymbolCount_Directoryname=78,SymbolCount_FileName=7,Entropy_URL=8,Entropy_Domain=78,Entropy_Filename=8,Entropy_Extension=7,Entropy_Afterpath=898,class=0)
test_set=rbind(test_set,dataframe)
training_set[1:45]=scale(training_set[1:45])
 test_set[1:45] = scale(test_set[1:45])
library(class)
y_pred = knn(train = training_set[,-46],test = test_set[, -46],cl = training_set[, 46], k = 5, prob = TRUE)
y_pred=tail(y_pred,1)
print(y_pred)