dataset=read.csv('Phishing.csv') 
   dataset = na.omit(dataset)
 dataset$class=factor(dataset$class,levels = c(0,1))
library(caTools)
set.seed(123)
   split= sample.split(dataset$class,SplitRatio = 0.75)
 training_set = subset(dataset, split == TRUE)
 test_set = subset(dataset, split == FALSE)
dataframe<-data.frame(Querylength=454,domain_token_count=541,path_token_count=45,longdomaintokenlen=1,avgpathtokenlen=54,tld=5241,charcompvowels=52,charcompace=412,ldl_url=111,ldl_path=111,ldl_getArg=4,dld_path=44,dld_getArg=12,pathLength=12,subDirLen=12,this.fileExtLen=12,ArgLen=12,ArgUrlRatio=11,domainUrlRatio=11,pathDomainRatio=1,NumberofDotsinURL=12,CharacterContinuityRate=12,URL_DigitCount=12,Extension_DigitCount=12,URL_Letter_Count=12,host_letter_count=125,Filename_LetterCount=12,Query_LetterCount=12,Domain_LongestWordLength=12,Path_LongestWordLength=22,Arguments_LongestWordLength=2,URL_sensitiveWord=1,spcharUrl=65,delimeter_path=2,NumberRate_URL=1,NumberRate_FileName=12,NumberRate_AfterPath=132,SymbolCount_URL=12,SymbolCount_Directoryname=12,SymbolCount_FileName=12,Entropy_URL=12,Entropy_Domain=12,Entropy_Filename=22,Entropy_Extension=12,Entropy_Afterpath=22,class=0)
test_set=rbind(test_set,dataframe)
training_set[1:45]=scale(training_set[1:45])
 test_set[1:45] = scale(test_set[1:45])
library(class)
y_pred = knn(train = training_set[,-46],test = test_set[, -46],cl = training_set[, 46], k = 5, prob = TRUE)
y_pred=tail(y_pred,1)
print(y_pred)